# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            SFCTA Prospector
tagline:          'so.much.data.'
description:      '"Just add data."'
url:              http://prospector.sfcta.org
baseurl:          /

author:
  name:           'SFCTA Staff'
  url:            http://www.sfcta.org

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/sfcta/prospector

gems: []
